### ISSUE TITLE
Test action not updating Aliases

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/skript-test-action#1]
I noticed when running a test action, that the aliases aren't updating.
from my workflow:
```yaml
...
-   name: Run tests
    uses: SkriptLang/skript-test-action@v1.1
    with:
        test_script_directory: src/test/scripts
        skript_repo_ref: 2.10.0-pre1
        extra_plugins_directory: extra-plugins/
        run_vanilla_tests: 'false' # temporarily disable, due to Skript's tests failing
```
Im attempting to run on 2.10.0-pre1...
this is in the action:
```sh
Cloning into '/skript'...
Submodule 'skript-aliases' (https://github.com/SkriptLang/skript-aliases) registered for path 'skript-aliases'
Cloning into '/skript/skript-aliases'...
Submodule path 'skript-aliases': checked out '16949c28e0d7bb25ea7c3479c3d6754ff3b5a3e6'
Note: switching to '2.10.0-pre1'.
```
After some digging, I see that `16949c2...` is Aliases from July 1/2024
https://github.com/SkriptLang/skript-aliases/commit/16949c28e0d7bb25ea7c3479c3d6754ff3b5a3e6

It appears to not properly check out the aliases that should be current.
(note also that skript 2.10.0's aliases are on another branch on the alias repo)
